CREATE DATABASE IF NOT EXISTS bid;

USE bid;

CREATE TABLE IF NOT EXISTS bid (
    bid_id INT AUTO_INCREMENT PRIMARY KEY,
    listing_id INT NOT NULL,
    buyer_id INT NOT NULL,
    amount FLOAT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);