DROP DATABASE IF EXISTS bid_db;
CREATE DATABASE IF NOT EXISTS bid_db;
USE bid_db;

CREATE TABLE bids (
    bid_id INT AUTO_INCREMENT PRIMARY KEY,
    listing_id INT NOT NULL,
    buyer_id INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
