DROP DATABASE IF EXISTS offer_db;
CREATE DATABASE IF NOT EXISTS offer_db;
USE offer_db; 

CREATE TABLE offers (
    offer_id INT AUTO_INCREMENT PRIMARY KEY,
    listing_id INT NOT NULL, 
    buyer_id INT NOT NULL, 
    seller_id INT NOT NULL, 
    amount DECIMAL(10,2) NOT NULL, 
    status VARCHAR(20) NOT NULL, 
    turn VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);